name: CI

on:
  push:
    branches:
      - master
  pull_request:
  # schedule:
  #   - cron: "0 23 * * 6"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        node_version:
          - "13"
          - "12"
          - "11"
          - "10"
          - "9"
          - "8"
          - "7"
          - "6"
          - "5"
          - "4"

    name: Node.js ${{ matrix.node_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    # needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install Dependencies
        if: matrix.node_version == '12'
        run: yarn

      - name: Run Test
        if: matrix.node_version != '12'
        run: yarn test

      - name: Run Test Coverage
        if: matrix.node_version == '12'
        run: yarn test-coverage

      - name: Upload Coverage
        uses: coverallsapp/github-action@master
        if: matrix.node_version == '12'
        continue-on-error: true
        with:
          github-token: ${{ secrets.github_token }}
          parallel: true

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Sending webhook to Coveralls
        uses: coverallsapp/github-action@master
        continue-on-error: true
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: "12"

      - name: Install Dependencies
        run: yarn

      - name: Run Lint
        run: yarn lint
